// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE-rhSbDBSJ04AufKlvSKa7ctdC1rNIdI',
    appId: '1:193049406964:web:3e5db236de13504e1e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    authDomain: 'push-notification-de9fc.firebaseapp.com',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
    measurementId: 'G-Q7HRP2T4Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKdsPVBqUlxbB7jbjIm8Vhx3l1DNdkBkM',
    appId: '1:193049406964:android:e1e641432397bc2c1e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCc9P0qY9GF-jbCufB2Q4QCwdibP4pkc',
    appId: '1:193049406964:ios:530a35d426966cfd1e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
    iosBundleId: 'com.example.workwista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCc9P0qY9GF-jbCufB2Q4QCwdibP4pkc',
    appId: '1:193049406964:ios:530a35d426966cfd1e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
    iosBundleId: 'com.example.workwista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE-rhSbDBSJ04AufKlvSKa7ctdC1rNIdI',
    appId: '1:193049406964:web:1801842e082e5d881e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    authDomain: 'push-notification-de9fc.firebaseapp.com',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
    measurementId: 'G-CZE2DEMW4G',
  );
}
