// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE-rhSbDBSJ04AufKlvSKa7ctdC1rNIdI',
    appId: '1:193049406964:web:c00c600edad22e141e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    authDomain: 'push-notification-de9fc.firebaseapp.com',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
    measurementId: 'G-7JMJF4BQJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKdsPVBqUlxbB7jbjIm8Vhx3l1DNdkBkM',
    appId: '1:193049406964:android:921d774f1c9ffa5d1e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCc9P0qY9GF-jbCufB2Q4QCwdibP4pkc',
    appId: '1:193049406964:ios:8bcccf8414748d6f1e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
    iosBundleId: 'com.example.workwista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCc9P0qY9GF-jbCufB2Q4QCwdibP4pkc',
    appId: '1:193049406964:ios:8bcccf8414748d6f1e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
    iosBundleId: 'com.example.workwista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE-rhSbDBSJ04AufKlvSKa7ctdC1rNIdI',
    appId: '1:193049406964:web:4c5bad50ad5678761e5da1',
    messagingSenderId: '193049406964',
    projectId: 'push-notification-de9fc',
    authDomain: 'push-notification-de9fc.firebaseapp.com',
    storageBucket: 'push-notification-de9fc.firebasestorage.app',
    measurementId: 'G-7M5WMYXNZE',
  );

}